import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from './providers/Providers'
import { StoreProvider } from '@/infraestructure/store/provider/StoreProvider'
import { Toaster } from 'react-hot-toast'

import { wrapper } from '@/infraestructure/store/store'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body className={`${inter.className} bg-slate-950 text-white min-h-screen px-5`}>
        <StoreProvider>
          <Providers>
            {children}
          </Providers>
          <Toaster />
        </StoreProvider>
      </body>
    </html>
  )
}

export default RootLayout;